In [3]:
import pickle
import pandas as pd
import numpy as np
#import detectda as dtda
import matplotlib.pyplot as plt
from skimage import filters
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import sys
from joblib import Parallel, delayed
from scipy.stats import mode

In [1]:
import bclr

In [4]:
file=open('experiment2_prior_kappa.pickle', 'rb')
exp2p=pickle.load(file)

In [9]:
cps = np.array([[y.post_k_mode for y in x] for x in exp2p])

In [10]:
np.mean(cps==40, axis=0)

array([0.583, 0.432, 0.516, 0.345])

In [13]:
np.std(cps==40, axis=0)/np.sqrt(1000)

array([0.01559202, 0.01566448, 0.01580329, 0.01503246])

In [18]:
def rmse(x):
    return np.sqrt(np.mean(x**2))

cp_bclr_mses_tda = np.array([[rmse(obj.post_k-40) for obj in bclr] for bclr in exp2p])

In [20]:
np.mean(cp_bclr_mses_tda, axis=0)

array([1.5372672 , 2.31053996, 2.49047528, 4.43609082])

In [21]:
np.std(cp_bclr_mses_tda, axis=0)

array([1.03182438, 1.99950201, 2.29919666, 4.48333521])

In [22]:
prior_cov = np.load("post_betas_cov40_INIT_R.npy")

In [24]:
np.diag(prior_cov)

array([0.60485283, 0.43756159, 0.30708787, 0.3043667 , 0.40049141,
       0.58778838, 0.56651868, 0.53356668, 0.45342077, 0.60017471,
       0.75023842, 0.82176453, 0.67868115, 0.64708949, 0.39654143,
       0.66033234, 0.43661679, 0.67417026, 0.62725161, 0.43042082,
       0.44957097, 0.41839994, 0.55250568, 0.62693416, 0.65184437,
       0.6253145 , 0.48893785, 0.49835215, 0.77881456, 0.80372662,
       0.67379576, 0.61654588, 0.4956093 , 0.63801852, 0.34217167,
       0.69457592])